app/modules/main/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from app import db, Base
from sqlalchemy.dialects.mysql import TINYINT, LONGTEXT


class SystemEvents(Base):
    __tablename__ = "system_events"

    event_type = db.Column(db.String(75), server_default="warning")
    event = db.Column(LONGTEXT)
    registration_timestamp = db.Column(db.DateTime, default=db.func.current_timestamp())
    event_seen = db.Column(TINYINT(1), server_default="0")

    def __init__(self, **kwargs):
        super(SystemEvents, self).__init__(**kwargs)

    def __repr__(self):
        return '<SystemEvent %r>' % self.id

app/modules/main/controllers.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from sqlalchemy import desc, and_
from flask import session
from app import logger, db
from app.extensions.response_ext import response_create
from app.extensions.security_ext import escape_chars, PasswordArgument
from app.extensions.db_ext import calculate_hash
from app.modules.auth.models import Users
from app.modules.main.models import SystemEvents


def list_system_events(fields, count, user_ip):
    try:
        available_fields = {
            "id": SystemEvents.id,
            "event_type": SystemEvents.event_type,
            "event_seen": SystemEvents.event_seen,
            "event": SystemEvents.event,
            "registration_timestamp": SystemEvents.registration_timestamp,
            "field_list": list()
        }
        # Set field option
        if fields:
            available_fields["field_list"].extend([available_fields[i] for i in fields.split(",") if i != "field_list"])
        else:
            available_fields["field_list"].extend([available_fields[i] for i in available_fields.keys() if i != "field_list"])
        system_event_object = SystemEvents.query.with_entities(
            *available_fields["field_list"]
        )
        system_event_info = system_event_object.order_by(
            desc(
                SystemEvents.registration_timestamp
            )
        )
        system_event_count = system_event_object.filter(
            SystemEvents.event_seen == 0
        ).count()
        if count:
            system_event_info = list()
        else:
            system_event_info = [i._asdict() for i in system_event_info.all()]
        return response_create({"status": "success", "data": system_event_info, "system_new_event_count": system_event_count})
    except Exception as e:
        logger.write_log(
            event_type="system-event-list",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})


def modify_system_events(post_form, user_ip):
    try:
        event_id = escape_chars(post_form["event_id"])
        system_event_object = SystemEvents.query.filter(
            and_(
                SystemEvents.id == event_id,
                SystemEvents.event_seen == 0
            )
        ).first()
        if system_event_object:
            system_event_object.event_seen = 1
            db.session.commit()
            log = "Event seen by '{0}'.".format(session.get("username"))
            logger.write_log(
                event_type="system-event-modify",
                event_severity="INFO",
                event_username="system",
                event_ip=user_ip,
                event=log
            )
        return response_create(
            data=dict()
        )
    except Exception as e:
        logger.write_log(
            event_type="system-event-modify",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})


def modify_user_password(post_form, user_ip):
    try:
        user_object = Users.query.filter(
            Users.id == session.get("user_id"),
            Users.password == calculate_hash(post_form["current_password"])
        ).first()
        if user_object:
            new_password = PasswordArgument(password=post_form["new_password"], re_password=post_form["confirm_new_password"]).play()
            user_object.password = new_password
            db.session.commit()
            log = "Password has been changed. Username: '{0}'.".format(session.get("username"))
            logger.write_log(
                event_type="user-password-modify",
                event_severity="INFO",
                event_username="system",
                event_ip=user_ip,
                event=log
            )
            return response_create({
                "status": "success",
                "message": "your password has been changed."
            })
        return response_create({
            "status": "error",
            "message": "Your current password does not match."
        })
    except Exception as e:
        logger.write_log(
            event_type="user-password-modify",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})

app/modules/main/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request
from app.extensions.wrappers import before_request_processing, login_required
from app.modules.main.controllers import list_system_events, modify_system_events, modify_user_password

main_router = Blueprint("main_router", __name__, url_prefix="/main")


@main_router.route("/dashboard", methods=["GET"])
@login_required
@before_request_processing(restricted=False)
def dashboard_page():
    return render_template(
        "main/dashboard.html"
    )


@main_router.route("/profile", methods=["GET"])
@login_required
@before_request_processing(restricted=False)
def profile_page():
    return render_template(
        "main/profile.html"
    )


@main_router.route("/profile/password/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_user_password_func():
    return modify_user_password(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@main_router.route("/system-events", methods=["GET"])
@login_required
@before_request_processing(restricted=False)
def system_events_page():
    return render_template(
        "main/system_events.html"
    )


@main_router.route("/system-events/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_system_events_func():
    return list_system_events(
        fields=request.args.get("fields", None),
        count=request.args.get("count", False),
        user_ip=request.headers.get("X-Forwarded-For")
    )


@main_router.route("/system-events/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_system_events_func():
    return modify_system_events(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )

app/templates/main/dashboard.html
{% extends "base.html" %}
{% block content %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
          <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
          <span data-feather="calendar"></span>
          This week
        </button>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6 box">
          <h4>Configuration Warnings</h4>
          <div>
            <span data-feather="check"></span>&nbsp; <label>All configurations are correct.</label>
          </div>
        </div>

        <div class="col-md-6 box">
          <h4>Configuration Tips</h4>
          <div>
            <span data-feather="frown"></span>&nbsp; <label>No tips found for your configurations.</label>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %} 

{% block js_content %}

  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>

{% endblock %}

app/templates/main/profile.html
{% extends "base.html" %}
{% block content %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Your Profile</h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="col-md-12 box">
          <h4>Information</h4>
          <div class="row">
            <div class="form-group col-md-2">
              <label class="form-title" for="user_id">User ID</label>
              <input type="text" class="form-control" id="user_id" disabled="disabled" value="{{  session.get('user_id') }}">
            </div>

            <div class="form-group col-md-2">
              <label class="form-title" for="username">Username</label>
              <input type="text" class="form-control" id="username" disabled="disabled" value="{{  session.get('username') }}">
            </div>

            <div class="form-group col-md-2">
              <label class="form-title" for="email">E-Mail</label>
              <input type="text" class="form-control" id="email" disabled="disabled" value="{{  session.get('email') }}">
            </div>

            <div class="form-group col-md-2">
              <label class="form-title" for="first_name">First Name</label>
              <input type="text" class="form-control" id="first_name" disabled="disabled" value="{{  session.get('first_name') }}">
            </div>

            <div class="form-group col-md-2">
              <label class="form-title" for="last_name">Last Name</label>
              <input type="text" class="form-control" id="last_name" disabled="disabled" value="{{  session.get('last_name') }}">
            </div>

            <div class="form-group col-md-2">
              <label class="form-title" for="role">Role</label>
              <input type="text" class="form-control" id="role" disabled="disabled" value="{{  session.get('role') }}">
            </div>
          </div>
        </div>

        <div class="col-md-6 box">
          <h4>Change Password</h4>
          <form id="change-password-form" method="POST" action="{{ url_for('main_router.modify_user_password_func') }}">
            <div class="form-group">
              <input type="password" class="form-control" name="current_password" placeholder="Current passwrod">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="new_password" placeholder="New passwrod">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="confirm_new_password" placeholder="Confirm new password">
            </div>
          </form>
          <button type="button" class="btn btn-info" style="width: 100%;" onclick="modify_user_password('change-password-form')">Change Now</button>
        </div>
    </div>
  </main>

{% endblock %} 

{% block js_content %}

  <script type="text/javascript" src="/static/frontend/js/custom_js/main.profile.js"></script>

{% endblock %}

app/templates/main/system_events.html
{% extends "base.html" %}
{% block css_content %}

  <link rel="stylesheet" type="text/css" href="/static/frontend/datatables/datatables.min.css">

{% endblock %}

{% block content %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">System Events</h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <table id="system-events-table" class="table table-hover" style="width:100%">
          <thead class="thead-dark">
              <tr>
                  <th>Event ID</th>
                  <th>Event Type</th>
                  <th>Event</th>
                  <th>Event Seen</th>
                  <th>Event Timestamp</th>
              </tr>
          </thead>
        </table>
      </div>
    </div>

  </main>

{% endblock %} 

{% block js_content %}

  <script type="text/javascript" src="/static/frontend/datatables/datatables.min.js"></script>
  <script type="text/javascript">
    
    $(document).ready(function() {
        var systemn_events_table = $('#system-events-table').DataTable( {
            "ajax": "/main/system-events/list",
            "columns": [
              { "data": "id" },
              { "data": "event_type" },
              { "data": "event" },
              { "data": "event_seen" },
              { "data": "registration_timestamp" }
            ],
            "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
              if ( aData.event_type == "error" && aData.event_seen == 0 ) {
                $("td", nRow).css("background-color", "#ad002a");
                $("td", nRow).css("color", "white");
              } else if ( aData.event_type == "warning" && aData.event_seen == 0 ) {
                $("td", nRow).css("background-color", "#e17700");
                $("td", nRow).css("color", "white");
              } else if ( aData.event_type == "success" && aData.event_seen == 0 ) {
                $("td", nRow).css("background-color", "#08ac00");
                $("td", nRow).css("color", "white");
              } else {
                $("td", nRow).css("background-color", "#acacac");
                $("td", nRow).css("color", "white");
              }
            },
            dom: "Bfrtip",
            buttons: [
              "copy", "excel", "pdf"
            ],
            "order": [[ 4, "desc" ]]
        });

        setInterval( function () {
            systemn_events_table.ajax.reload();
        }, 30000 );

        $( document ).on("click", "tr[role='row']", function(){
            var event_id = $(this).children('td:first-child').text();
            $.ajax({
              type: "POST",
              url: "/main/system-events/modify",
              data: {"event_id": event_id},
              dataType: "json",
              success: function(data) {
                  get_new_events_count();
                  systemn_events_table.ajax.reload();
              }
          });
        });
    });

  </script>

{% endblock %}