app/modules/clusters/controllers.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from sqlalchemy import desc, and_
from crossplane import build
from flask import session
from app import db, logger
from app.extensions.response_ext import response_create
from app.extensions.general_ext import get_host_group_alias, get_host_group_id, sqlalchemy_as_dict, nginx_config_parser
from app.extensions.security_ext import escape_chars, BoolStringArgument
from app.extensions.db_ext import calculate_hash, get_unix_timestamp
from app.modules.admin.models import HostGroups
from app.modules.agent.models import Hosts, NginxConfiguration


def list_hosts_information(user_ip):
    try:
        hosts_with_host_group = dict()
        hosts_info = Hosts.query.with_entities(
            Hosts.id,
            Hosts.hostname,
            Hosts.primary_address,
            Hosts.hypervisor,
            Hosts.running,
            Hosts.os_info,
            Hosts.nginx_package_version,
            Hosts.host_group,
            Hosts.status,
            Hosts.tags
        ).filter(
            Hosts.deleted == 0
        ).order_by(
            desc(
                Hosts.registration_timestamp
            )
        ).all()
        for host in hosts_info:
            host_object = list(host)
            host_group = get_host_group_alias(host_group_id=host.host_group)
            host_object.append(host_group)
            if host_group in hosts_with_host_group.keys():
                hosts_with_host_group[host_group].append(host_object)
            else:
                hosts_with_host_group[host_group] = [
                    host_object
                ]
        return response_create({"status": "success", "hosts_info": hosts_with_host_group})
    except Exception as e:
        logger.write_log(
            event_type="hosts-list",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})


def modify_host(post_form, user_ip):
    try:
        status = BoolStringArgument(target=post_form["status"], data_type="Status").play()
        host_group_id = escape_chars(post_form["host_group"])
        host_id = escape_chars(post_form["host_id"])
        host_object = Hosts.query.filter(
            and_(
                Hosts.id == host_id,
                Hosts.deleted == 0
            )
        ).first()
        if host_object:
            is_changed = False
            changes = dict()
            if host_object.status != status:
                is_changed = True
                changes["status"] = {
                    "old": host_object.status,
                    "new": status
                }
                host_object.status = status
            if host_object.host_group != host_group_id:
                is_changed = True
                changes["host_group"] = {
                    "old": get_host_group_alias(host_group_id=host_object.host_group),
                    "new": get_host_group_alias(host_group_id=host_group_id)
                }
                # TODO: Create database function for this
                new_host_group_object = HostGroups.query.filter(
                    HostGroups.id == host_group_id,
                ).first()
                old_host_group_object = HostGroups.query.filter(
                    HostGroups.id == host_object.host_group,
                ).first()
                new_host_group_object.registered_host_count += 1
                old_host_group_object.registered_host_count -= 1
                host_object.host_group = host_group_id
            if is_changed:
                db.session.commit()
                log = "Host modified. Changes: '{0}', Username: '{1}', Hostname: '{2}'.".format("; ".join([k + ": " + str(v) for k, v in changes.items()]), session.get("username"), host_object.hostname)
                logger.write_log(
                    event_type="host-modify",
                    event_severity="INFO",
                    event_username="system",
                    event_ip=user_ip,
                    event=log
                )
                return response_create({
                    "status": "success",
                    "message": "Host modified.",
                })
        return response_create({
            "status": "warning",
            "message": "Nothings changed."
        })
    except Exception as e:
        logger.write_log(
            event_type="hosts-modify",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})


def delete_host(host_id, user_ip):
    try:
        host_object = Hosts.query.filter(
            and_(
                Hosts.id == host_id,
                Hosts.deleted == 0
            )
        ).first()
        if host_object:
            host_group_object = HostGroups.query.filter(
                HostGroups.id == host_object.host_group
            ).first()
            host_group_object.registered_host_count -= 1
            host_object.deleted = 1
            db.session.commit()
            log = "Host deleted. Username: '{0}', Hostname: '{1}'.".format(session.get("username"), host_object.hostname)
            logger.write_log(
                event_type="host-delete",
                event_severity="INFO",
                event_username="system",
                event_ip=user_ip,
                event=log
            )
            return response_create({
                "status": "success",
                "message": "Removing the system will remove all of the objects below. Do not forget to stop the Amplify Agent on the host, otherwise the system will reappear in the user interface"
            })
    except Exception as e:
        logger.write_log(
            event_type="host-delete",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})


def list_host_information(host_id, user_ip):
    try:
        host_info = Hosts.query.filter(
            and_(
                Hosts.deleted == 0,
                Hosts.id == host_id
            )
        ).first()
        host_info_dict = sqlalchemy_as_dict(result_proxy=host_info)
        host_info_dict["host_group_name"] = get_host_group_alias(host_group_id=host_info_dict["host_group"])
        return response_create({"status": "success", "host_info": host_info_dict})
    except Exception as e:
        logger.write_log(
            event_type="hosts-list",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )
        return response_create({"status": "error", "message": str(e)})


def list_host_group_configuration_information(host_group_name, user_ip):
    try:
        host_group_configuration_info = NginxConfiguration.query.filter(
            NginxConfiguration.host_group == get_host_group_id(host_group_name)
        ).all()
        return host_group_configuration_info
    except Exception as e:
        logger.write_log(
            event_type="host-group-configuration-list",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )


def modify_clusters_configuration(post_form, user_ip):
    try:
        configuration = escape_chars(post_form["configuration"])
        host_group_id = escape_chars(post_form["host_group_id"])
        config_id = escape_chars(post_form["config_id"])
        configuration_object = NginxConfiguration.query.filter(
            and_(
                NginxConfiguration.host_group == host_group_id,
                NginxConfiguration.id == config_id
            )
        ).first()
        if configuration_object:
            new_config_object = nginx_config_parser(configuration)
            new_configuration = build(new_config_object["config"][0]["parsed"])
            config_content_hash = calculate_hash(new_configuration)
            if configuration_object.config_content_hash != config_content_hash:
                all_hosts_object = Hosts.query.filter(
                    and_(
                        Hosts.host_group == configuration_object.host_group,
                        Hosts.deleted == 0
                    )
                ).all()
                for host in all_hosts_object:
                    host.latest_config = 0
                # TODO: Take a backup for old configurations
                configuration_object.config_content = new_configuration
                configuration_object.config_content_hash = config_content_hash
                configuration_object.config_file_modify_time = get_unix_timestamp()
                configuration_object.config_update_required = 1
                db.session.commit()
                log = "Configuration modified by '{0}'. Host Group: '{1}'.".format(session.get("username"), get_host_group_alias(configuration_object.host_group))
                logger.write_log(
                    event_type="cluster-lb-configuration-modify",
                    event_severity="INFO",
                    event_username="system",
                    event_ip=user_ip,
                    event=log
                )
                return response_create({
                    "status": "success",
                    "message": "Configuration changed."
                })
        return response_create({
            "status": "warning",
            "message": "Nothings changed."
        })
    except Exception as e:
        logger.write_log(
            event_type="cluster-lb-configuration-modify",
            event_severity="ERROR",
            event_username="system",
            event_ip=user_ip,
            event=e
        )

app/modules/clusters/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request
from app.extensions.wrappers import before_request_processing, login_required
from app.extensions.db_ext import datetime_from_timestamp
from app.extensions.general_ext import get_host_group_id
from app.modules.clusters.controllers import list_hosts_information, modify_host, delete_host, list_host_information, list_host_group_configuration_information, modify_clusters_configuration

clusters_router = Blueprint("clusters_router", __name__, url_prefix="/clusters")


@clusters_router.route("/", methods=["GET"])
@login_required
@before_request_processing(restricted=False)
def clusters_dashboard_page():
    return render_template(
        "clusters/dashboard.html"
    )


@clusters_router.route("/cluster/lb/configuration/<cluster_name>", methods=["GET"])
@login_required
@before_request_processing(restricted=False)
def clusters_configuration_page(cluster_name):
    return render_template(
        "clusters/lb_configuration.html",
        cluster_namne=cluster_name,
        host_group_id=get_host_group_id(cluster_name),
        host_group_config_info=list_host_group_configuration_information(
            host_group_name=cluster_name,
            user_ip=request.headers.get("X-Forwarded-For")
        ),
        timestamp_converter=datetime_from_timestamp
    )


@clusters_router.route("/hosts/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_hosts_func():
    return list_hosts_information(
        user_ip=request.headers.get("X-Forwarded-For")
    )


@clusters_router.route("/hosts/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_host_func():
    return modify_host(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@clusters_router.route("/hosts/delete/<host_id>", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def delete_host_func(host_id):
    return delete_host(
        host_id=host_id,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@clusters_router.route("/hosts/host-info/<host_id>", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_host_info_func(host_id):
    return list_host_information(
        host_id=host_id,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@clusters_router.route("/cluster/lb/configuration/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_clusters_configuration_func():
    return modify_clusters_configuration(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )

app/templates/clusters/dashboard.html
{% extends "base.html" %}
{% block modal_content %}

  <div class="modal fade" id="host-modify" tabindex="-1" role="dialog" aria-labelledby="host-modify-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="host-modify-label">Modify <label name="hostname" style="font-weight: bolder;"></label> Host</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form id="host-modify-form" method="POST" action="{{ url_for('clusters_router.modify_host_func') }}">
            <div class="row">

              <div class="col-md-6">
                <div class="form-group">
                  <select class="selectpicker form-control" name="status">
                    <option value="" selected disabled>Status</option>
                    <option value="Active">Active</option>
                    <option value="Deactive">Deactive</option>
                  </select>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <select class="selectpicker form-control" name="host_group">
                    <option value="" selected disabled>Host Group</option>
                  </select>
                </div>
              </div>
            </div>

            <input type="text" name="host_id" hidden="hidden">
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-danger" onclick="delete_host()">Delete Host</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-info" onclick="modify_host('host-modify-form')">Save Now</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="host-info" tabindex="-1" role="dialog" aria-labelledby="host-info-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="host-info-label">Information About <label name="hostname" style="font-weight: bolder;"></label></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <div class="row">
            <div class="col-md-12">
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" id="system-tab" data-toggle="tab" href="#system" role="tab" aria-controls="system" aria-selected="true">System</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="nginx-tab" data-toggle="tab" href="#nginx" role="tab" aria-controls="nginx" aria-selected="false">Nginx</a>
                </li>
              </ul>
              <div class="tab-content" id="info-tab-content">
                <div class="tab-pane fade show active" id="system" role="tabpanel" aria-labelledby="system-tab">
                  <div class="row" style="margin-top: 3%;">
                    <div class="col-md-12">
                      <h2 style="font-weight: bolder;">System Objects</h2>
                      <h5 style="font-weight: bolder; margin-top: 2%;">General</h5>
                      <p class="item">Hostname: <label class="item" name="sysobj-hostname"></label></p>
                      <p class="item">Status: <label class="item" name="sysobj-status"></label></p>
                      <p class="item">Last Seen: <label class="item" name="sysobj-last-seen"></label></p>
                      <p class="item">Created: <label class="item" name="sysobj-created"></label></p>
                      <p class="item">Host Group: <label class="item" name="sysobj-host-group"></label></p>
                      <h5 style="font-weight: bolder; margin-top: 2%;">Operating system</h5>
                      <p class="item">Version: <label class="item" name="sysobj-os-version"></label></p>
                      <p class="item">uptime: <label class="item" name="sysobj-os-uptime"></label></p>
                      <h5 style="font-weight: bolder; margin-top: 2%;">Hardware</h5>
                      <p class="item">Hypervisor: <label class="item" name="sysobj-hypervisor"></label></p>
                    </div>
                  </div>
                </div>
                <div class="tab-pane fade" id="nginx" role="tabpanel" aria-labelledby="nginx-tab">
                  <div class="row" style="margin-top: 3%;">
                    <div class="col-md-12">
                      <h2 style="font-weight: bolder;">Nginx Objects</h2>
                      <h5 style="font-weight: bolder; margin-top: 2%;">General</h5>
                      <p class="item">Status: <label class="item" name="ngobj-status"></label></p>
                      <p class="item">Packages: <label class="item" name="ngobj-version"></label></p>
                      <p class="item">Amplify Agent Version: <label class="item" name="ngobj-agent-version"></label></p>
                      <p class="item">Amplify Agent UUID: <label class="item" name="ngobj-agent-uuid"></label></p>
                      <p class="item">Stub Status Enabled: <label class="item" name="ngobj-stub-status-enabled"></label></p>
                      <p class="item">Built From Source: <label class="item" name="ngobj-built-from-source"></label></p>
                      <p class="item">Tags: <label class="item" name="ngobj-tags"></label></p>

                      <h5 style="font-weight: bolder; margin-top: 2%;">Configure args</h5>
                      <div id="configure-args-area">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block content %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Clusters Dashboard</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
          <button type="button" class="btn btn-sm btn-outline-secondary" onclick="go_to_cluster_configuration()">Cluster Configuration</button>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-tabs" id="clusters-nav-tabs" role="tablist">

        </ul>

        <div class="tab-content" id="nav-tabs-area">

        </div>
      </div>
    </div>
  </main>

{% endblock %} 

{% block js_content %}

  <script type="text/javascript" src="/static/frontend/js/custom_js/clusters.js"></script>
  <script type="text/javascript">
    
    $(document).ready(function() {
      list_hosts_information();
    })

  </script>

{% endblock %}

app/templates/clusters/lb_configuration.html
{% extends "base.html" %}

{% block css_content %}

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js"></script>

{% endblock %}

{% block content %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2"><label class="form-title cluster-name">{{ cluster_namne }}</label> Cluster Configuration</h1>
    </div>

    <input type="text" id="host_group_id" value="{{ host_group_id }}" hidden="hidden">

    <div class="row">
      <div class="col-md-3">
        <div class="nav flex-column nav-pills" id="config-objects-tab" role="tablist" aria-orientation="vertical">

          {% for file_name in host_group_config_info %}

            {% if file_name['config_status'] == "ok" %}
              {% set badge_color = "info" %}
            {% else %}
              {% set badge_color = "danger" %}
            {% endif %}

            {% set changes_pending = "" %}
            {% if file_name["config_update_required"] == 1 %}
              {% set changes_pending = "<span style='float: right; margin-top: 2px;' class='badge badge-pill badge-warning'>Syncing</span>" %}
            {% endif %}

            {% if file_name["config_update_failed"] == 1 %}
              {% set changes_pending = "<span style='float: right; margin-top: 2px;' class='badge badge-pill badge-danger'>Sync Failed</span>" %}
            {% endif %}

            <a class="nav-link" id="config-objects-tab-{{ file_name['id'] }}" data-toggle="pill" href="#config-objects-{{ file_name['id'] }}" role="tab" aria-controls="config-objects-{{ file_name['id'] }}" aria-selected="true">{{ file_name['config_file'] }} <span style="float: right; margin-top: 2px;" class="badge badge-pill badge-{{ badge_color }}">{{ file_name['config_status'] }}</span> {{ changes_pending|safe }}</a>

          {% endfor %}

        </div>
      </div>
      <div class="col-md-9">
        <div class="tab-content" id="config-objects-tab-content">

          {% for config_object in host_group_config_info %}

            {% if config_object['config_status'] == "ok" %}
              {% set text_color = "green" %}
            {% else %}
              {% set text_color = "red" %}
            {% endif %}

            <div class="tab-pane fade box" id="config-objects-{{ config_object['id'] }}" role="tabpanel" aria-labelledby="config-objects-tab">
              <div class="row">

                <div class="col-md-4">
                  <h3>General Information</h3><br>
                  <label class="config-item">Config Status: <label class="form-title config-item" style="color: {{ text_color }};">{{ config_object['config_status'] }}</label></label><br>
                  <label class="config-item">Config File Name: <label class="form-title config-item">{{ config_object['config_file'] }}</label></label><br>
                  <label class="config-item">Last Modified: <label class="form-title config-item">{{ timestamp_converter(config_object['config_file_modify_time']) }}</label></label><br>
                  <label class="config-item">Total Lines: <label class="form-title config-item">{{ config_object['config_file_lines'] }}</label></label><br>

                  {% if config_object["config_errors"]|length > 0 %}
                    {% set errors = config_object["config_errors"].split(';') %}

                    <h3>Erros</h3>
                    <ul>
                          
                      {% for error in errors %}

                        <li class="error-text">{{ error }}</li>

                      {% endfor %}

                    </ul>

                  {% endif %}
                </div>

                <div class="col-md-8 editor" id="editor-{{ config_object['id'] }}">{{ config_object['config_content']|safe }}</div>
                <script type="text/javascript">
                  var editor_{{ config_object['id'] }} = ace.edit("editor-{{ config_object['id'] }}");
                  editor_{{ config_object['id'] }}.setTheme("ace/theme/monokai");
                  editor_{{ config_object['id'] }}.session.setMode("ace/mode/nginx");
                  editor_{{ config_object['id'] }}.setHighlightActiveLine(true);
                  editor_{{ config_object['id'] }}.session.setUseWrapMode(true);
                  var modified_{{ config_object['id'] }} = 'ace-changed'; // css class
                  editor_{{ config_object['id'] }}.on('change', function(e) {
                    var activeLine = e.start.row;
                    if (e.action == "insert") {
                      while (activeLine < (e.end.row+1)) {
                        editor_{{ config_object['id'] }}.session.removeGutterDecoration(activeLine, modified_{{ config_object['id'] }});
                        editor_{{ config_object['id'] }}.session.addGutterDecoration(activeLine, modified_{{ config_object['id'] }});
                        activeLine++;
                      }
                    } else if (e.action == "remove") {
                      while (activeLine < (e.end.row+1)) {
                        editor_{{ config_object['id'] }}.session.removeGutterDecoration(activeLine, modified_{{ config_object['id'] }});
                        activeLine++;
                      }
                      editor_{{ config_object['id'] }}.session.addGutterDecoration(e.start.row, modified_{{ config_object['id'] }});
                    }
                  });
                </script>

              </div>

              <div class="col-md-12">
                <button type="button" class="btn btn-lg btn-info" style="float: right; margin-top: 5px; width: 100%;" onclick="modify_cluster_config('{{ config_object['id'] }}')">Save Config</button>
              </div>
            </div>

          {% endfor %}
          
        </div>
      </div>
    </div>
  </main>

{% endblock %} 

{% block js_content %}

  <script type="text/javascript" src="/static/frontend/js/custom_js/clusters.js"></script>
  <script type="text/javascript">
    
    $(document).ready(function() {
      $("#config-objects-tab a:first").tab("show");
    });

  </script>

{% endblock %}