app/modules/admin/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request
from app.extensions.wrappers import before_request_processing, login_required
from app.modules.admin.controllers import create_agent_api_key, list_agent_api_key_information, modify_agent_api_key, delete_agent_api_key, create_host_group, list_host_group_information, modify_host_group, delete_host_group, create_user, list_user_information, modify_user, delete_user, list_user_role_information, list_page_information

admin_router = Blueprint("admin_router", __name__, url_prefix="/admin")


@admin_router.route("/settings", methods=["GET"])
@login_required
@before_request_processing(restricted=False)
def settings_page():
    return render_template(
        "admin/settings.html"
    )


@admin_router.route("/agent/api-key/create", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def create_agent_api_key_func():
    return create_agent_api_key(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/api-key/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_agent_api_key_func():
    return list_agent_api_key_information(
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/api-key/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_agent_api_key_func():
    return modify_agent_api_key(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/api-key/delete/<key_id>", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def delete_agent_api_key_func(key_id):
    return delete_agent_api_key(
        api_key_id=key_id,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/host-group/create", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def create_host_group_func():
    return create_host_group(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/host-group/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_host_group_func():
    return list_host_group_information(
        fields=request.args.get("fields", None),
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/host-group/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_host_group_func():
    return modify_host_group(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/agent/host-group/delete/<host_group_id>", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def delete_host_group_func(host_group_id):
    return delete_host_group(
        host_group_id=host_group_id,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/users/user/create", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def create_user_func():
    return create_user(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/users/user/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_user_func():
    return list_user_information(
        fields=request.args.get("fields", None),
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/users/user/modify", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def modify_user_func():
    return modify_user(
        post_form=request.form,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/users/user/delete/<user_id>", methods=["POST"])
@login_required
@before_request_processing(restricted=True)
def delete_user_func(user_id):
    return delete_user(
        user_id=user_id,
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/users/user-role/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_user_role_func():
    return list_user_role_information(
        fields=request.args.get("fields", None),
        user_ip=request.headers.get("X-Forwarded-For")
    )


@admin_router.route("/pages/list", methods=["GET"])
@login_required
@before_request_processing(restricted=True)
def list_page_func():
    return list_page_information(
        fields=request.args.get("fields", None),
        user_ip=request.headers.get("X-Forwarded-For")
    )

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{{ page_title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="/static/frontend/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

    <!-- Tags css -->
    <link rel="stylesheet" type="text/css" href="/static/frontend/css/tagsinput.css">

    <!-- Bootstrap select css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

    <!-- Custom css -->
    <link rel="stylesheet" type="text/css" href="/static/frontend/css/custom_css/custom.css">

    {% block css_content %} {% endblock %}


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="/static/frontend/css/dashboard.css" rel="stylesheet">
  </head>
  <body>

    <img src="/static/images/loading.gif" class="loading-image">

    {% block modal_content %} {% endblock %}

      <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Nginx Controller</a>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <a class="nav-link profile-link" href="/main/profile">Profile</a>
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{{ url_for('auth_router.user_logout') }}">Sign out</a>
          </li>
        </ul>
      </nav>

      <div class="container-fluid">
        <div class="row">
          <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
              <ul class="nav flex-column">

                {% for page in session.get("pages") %}

                  {% set is_active = "" %}
                  {% if request.path.startswith(page.location) %}
                    {% set is_active = "active" %}
                  {% endif %}

                    <li class="nav-item">
                      <a class="nav-link {{ is_active }}" href="{{ page.location }}">
                        <span data-feather="{{ page.icon }}"></span>
                        {{ page.name }}
                        <span class="sr-only">(current)</span>
                        <span class="badge badge-danger" style="float: right; margin-top: 3px;" id="{{ page.name| replace(' ', '') }}"></span>
                      </a>
                    </li>

                {% endfor %}

                {% if session.get("role") == "Admin" %}
                  {% set is_active = "" %}
                  {% if request.path.startswith(url_for('admin_router.settings_page')) %}
                    {% set is_active = "active" %}
                  {% endif %}

                    <li class="nav-item">
                      <a class="nav-link {{ is_active }}" href="{{ url_for('admin_router.settings_page') }}">
                        <span data-feather="settings"></span>
                        Settings
                      </a>
                    </li>

                {% endif %}

              </ul>
            </div>
          </nav>

          {% block content %} {% endblock %}

        </div>
      </div>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="/static/frontend/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
      <script type="text/javascript" src="/static/frontend/js/tagsinput.js"></script>
      <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>
      {% block js_content %} {% endblock %}
      <script type="text/javascript">
        
        feather.replace();

        get_new_events_count();

        setInterval(function() {
          get_new_events_count();
        }, 5000);

        function get_new_events_count() {
          $.ajax({
            type: "GET",
            url: "/main/system-events/list?count=True",
            dataType: "json",
            success: function(data) {
                if (data.system_new_event_count > 0) {
                  $("#SystemEvents").text(data.system_new_event_count+" New Event");
                } else if (data.system_new_event_count == 0) {
                  $("#SystemEvents").text("");
                }
            }
          });
        }

      </script>
    </body>
</html>

app/templates/signin.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{{ page_title }}</title>


    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="/static/frontend/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="/static/frontend/css/signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <form id="sign-in-form" class="form-signin" method="POST" action="{{ url_for('auth_router.user_login') }}">
      <img class="mb-4" src="{{ project_logo }}" alt="" width="300" height="200">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="user_email_or_username" class="sr-only">Email address</label>
      <input type="text" id="user_email_or_username" name="user_email_or_username" class="form-control" placeholder="Email address or Username" required autofocus>
      <label for="password" class="sr-only">Password</label>
      <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
      <button class="btn btn-lg btn-info btn-block" type="button" onclick="sign_in('sign-in-form')">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; {{ footer_text }}</p>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="/static/frontend/js/custom_js/sign.in.js"></script>
    <script type="text/javascript">
      
      {% if account_status_changed_sign %}
        swal({
            position: 'top-end',
            icon: "warning",
            title: "Your account modified. You have to login again.",
            timer: 5000
        });
      {% endif %}

    </script>
  </body>
</html>